"""initial_schema

Revision ID: ff6bf89acc4e
Revises:
Create Date: 2026-07-16 00:03:54.662120
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ff6bf89acc4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_login_attempt_lookup",
            ["username", "ip_address", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_username"), ["username"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_code", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('OWNER','HORSE_KEEPER','CATTLE_KEEPER','SHEEP_KEEPER')",
            name="ck_users_role",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("module", sa.String(length=80), nullable=True),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=120), nullable=True),
        sa.Column("previous_data", sa.Text(), nullable=True),
        sa.Column("new_data", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_module"), ["module"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_role"), ["role"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_username"), ["username"], unique=False
        )

    op.create_table(
        "dashboard_preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("visible_widgets", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "finance_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("livestock_module", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "category IS NULL OR category IN ('Малчинд','Өвс тэжээлд','Татварт','Хашаа хороонд','Бусад ажлын хөлсөнд','Түлшинд','Бусад')",
            name="ck_finance_category",
        ),
        sa.CheckConstraint(
            "entry_type IN ('INCOME','EXPENSE')", name="ck_finance_type"
        ),
        sa.CheckConstraint(
            "livestock_module IN ('horses','cattle','small_livestock','general')",
            name="ck_finance_module",
        ),
        sa.CheckConstraint("amount > 0", name="ck_finance_amount_positive"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finance_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_finance_entries_archived_at"), ["archived_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_entry_date"), ["entry_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_entry_type"), ["entry_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_livestock_module"),
            ["livestock_module"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_entries_updated_by"), ["updated_by"], unique=False
        )

    op.create_table(
        "herders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=120), nullable=False),
        sa.Column("first_name", sa.String(length=120), nullable=False),
        sa.Column("registration_number", sa.String(length=30), nullable=False),
        sa.Column("started_date", sa.Date(), nullable=False),
        sa.Column("ended_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "module IN ('horses','cattle','small_livestock')", name="ck_herders_module"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "registration_number", name="uq_herders_registration_number"
        ),
    )
    with op.batch_alter_table("herders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_herders_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_herders_first_name"), ["first_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_herders_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_herders_module"), ["module"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_herders_updated_by"), ["updated_by"], unique=False
        )

    op.create_table(
        "horse_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("horse_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_horse_groups_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_horse_groups_name"), ["name"], unique=True)

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uq_idempotency_user_key"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_records_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "image_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_type", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('MAIN','DETAIL','LAYOUT')", name="ck_images_kind"),
        sa.CheckConstraint(
            "owner_type IN ('horse','cattle')", name="ck_images_owner_type"
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND width > 0 AND height > 0", name="ck_images_dimensions"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("image_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_assets_checksum_sha256"),
            ["checksum_sha256"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_image_assets_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            "ix_images_owner", ["owner_type", "owner_id", "kind"], unique=False
        )

    op.create_table(
        "inventory_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=30), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "module IN ('horses','cattle','small_livestock')",
            name="ck_snapshots_module",
        ),
        sa.CheckConstraint("count >= 0", name="ck_snapshots_count_nonnegative"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module", "snapshot_date", name="uq_snapshot_module_date"),
    )
    with op.batch_alter_table("inventory_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_snapshots_created_by"),
            ["created_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_snapshots_module"), ["module"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_snapshots_snapshot_date"),
            ["snapshot_date"],
            unique=False,
        )

    op.create_table(
        "small_livestock_counts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("count_type", sa.String(length=20), nullable=False),
        sa.Column("count_date", sa.Date(), nullable=False),
        sa.Column("sheep_male", sa.Integer(), nullable=False),
        sa.Column("sheep_female", sa.Integer(), nullable=False),
        sa.Column("goat_male", sa.Integer(), nullable=False),
        sa.Column("goat_female", sa.Integer(), nullable=False),
        sa.Column("male_lamb", sa.Integer(), nullable=False),
        sa.Column("female_lamb", sa.Integer(), nullable=False),
        sa.Column("male_kid", sa.Integer(), nullable=False),
        sa.Column("female_kid", sa.Integer(), nullable=False),
        sa.Column("hogget", sa.Integer(), nullable=False),
        sa.Column("yearling_goat", sa.Integer(), nullable=False),
        sa.Column("ram", sa.Integer(), nullable=False),
        sa.Column("buck", sa.Integer(), nullable=False),
        sa.Column("evening_sheep_total", sa.Integer(), nullable=True),
        sa.Column("evening_goat_total", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "count_type IN ('FULL','EVENING')", name="ck_small_counts_type"
        ),
        sa.CheckConstraint("buck >= 0", name="ck_small_counts_buck_nonnegative"),
        sa.CheckConstraint(
            "evening_goat_total IS NULL OR evening_goat_total >= 0",
            name="ck_evening_goat_nonnegative",
        ),
        sa.CheckConstraint(
            "evening_sheep_total IS NULL OR evening_sheep_total >= 0",
            name="ck_evening_sheep_nonnegative",
        ),
        sa.CheckConstraint(
            "female_kid >= 0", name="ck_small_counts_female_kid_nonnegative"
        ),
        sa.CheckConstraint(
            "female_lamb >= 0", name="ck_small_counts_female_lamb_nonnegative"
        ),
        sa.CheckConstraint(
            "goat_female >= 0", name="ck_small_counts_goat_female_nonnegative"
        ),
        sa.CheckConstraint(
            "goat_male >= 0", name="ck_small_counts_goat_male_nonnegative"
        ),
        sa.CheckConstraint("hogget >= 0", name="ck_small_counts_hogget_nonnegative"),
        sa.CheckConstraint(
            "male_kid >= 0", name="ck_small_counts_male_kid_nonnegative"
        ),
        sa.CheckConstraint(
            "male_lamb >= 0", name="ck_small_counts_male_lamb_nonnegative"
        ),
        sa.CheckConstraint("ram >= 0", name="ck_small_counts_ram_nonnegative"),
        sa.CheckConstraint(
            "sheep_female >= 0", name="ck_small_counts_sheep_female_nonnegative"
        ),
        sa.CheckConstraint(
            "sheep_male >= 0", name="ck_small_counts_sheep_male_nonnegative"
        ),
        sa.CheckConstraint(
            "yearling_goat >= 0", name="ck_small_counts_yearling_goat_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "count_type", "count_date", name="uq_small_count_type_date"
        ),
    )
    with op.batch_alter_table("small_livestock_counts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_livestock_counts_count_date"),
            ["count_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_counts_count_type"),
            ["count_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_counts_created_by"),
            ["created_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_counts_updated_by"),
            ["updated_by"],
            unique=False,
        )

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_sessions_refresh_token_hash"),
            ["refresh_token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_user_sessions_revoked_at"), ["revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "cattle",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ear_tag", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=160), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("is_bull", sa.Boolean(), nullable=False),
        sa.Column("current_status", sa.String(length=30), nullable=False),
        sa.Column("mother_id", sa.String(length=36), nullable=True),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("main_image_id", sa.String(length=36), nullable=True),
        sa.Column("layout_image_id", sa.String(length=36), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_note", sa.Text(), nullable=True),
        sa.Column("unnatural_loss", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(current_status IN ('ARCHIVED','DECEASED')) = (archived_at IS NOT NULL)",
            name="ck_cattle_archive_state",
        ),
        sa.CheckConstraint("NOT is_bull OR sex = 'MALE'", name="ck_cattle_bull_male"),
        sa.CheckConstraint(
            "current_status IN ('ACTIVE','ARCHIVED','DECEASED')",
            name="ck_cattle_status",
        ),
        sa.CheckConstraint("sex IN ('MALE','FEMALE')", name="ck_cattle_sex"),
        sa.CheckConstraint(
            "birth_year >= 1980 AND birth_year <= 2100", name="ck_cattle_birth_year"
        ),
        sa.CheckConstraint(
            "mother_id IS NULL OR mother_id <> id", name="ck_cattle_not_own_mother"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["layout_image_id"],
            ["image_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["main_image_id"],
            ["image_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["cattle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cattle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cattle_birth_year"), ["birth_year"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cattle_color"), ["color"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cattle_current_status"), ["current_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cattle_ear_tag"), ["ear_tag"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_cattle_is_bull"), ["is_bull"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cattle_mother_id"), ["mother_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cattle_sex"), ["sex"], unique=False)

    op.create_table(
        "horses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.Column("color", sa.String(length=160), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("male_status", sa.String(length=20), nullable=True),
        sa.Column("current_status", sa.String(length=30), nullable=False),
        sa.Column("mother_id", sa.String(length=36), nullable=True),
        sa.Column("father_id", sa.String(length=36), nullable=True),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("main_image_id", sa.String(length=36), nullable=True),
        sa.Column("layout_image_id", sa.String(length=36), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_note", sa.Text(), nullable=True),
        sa.Column("unnatural_loss", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(current_status IN ('ARCHIVED','DECEASED')) = (archived_at IS NOT NULL)",
            name="ck_horses_archive_state",
        ),
        sa.CheckConstraint(
            "current_status IN ('ACTIVE','PREGNANT','ARCHIVED','DECEASED')",
            name="ck_horses_status",
        ),
        sa.CheckConstraint(
            "male_status IS NULL OR male_status IN ('STALLION','GELDING','COLT')",
            name="ck_horses_male_status",
        ),
        sa.CheckConstraint("sex IN ('MALE','FEMALE')", name="ck_horses_sex"),
        sa.CheckConstraint(
            "birth_year >= 1980 AND birth_year <= 2100", name="ck_horses_birth_year"
        ),
        sa.CheckConstraint(
            "father_id IS NULL OR father_id <> id", name="ck_horses_not_own_father"
        ),
        sa.CheckConstraint(
            "mother_id IS NULL OR mother_id <> id", name="ck_horses_not_own_mother"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["father_id"],
            ["horses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["horse_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["layout_image_id"],
            ["image_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["main_image_id"],
            ["image_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["horses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("horses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_horses_birth_year"), ["birth_year"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_horses_color"), ["color"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_horses_current_status"), ["current_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_horses_father_id"), ["father_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_horses_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_horses_male_status"), ["male_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_horses_mother_id"), ["mother_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_horses_sex"), ["sex"], unique=False)

    op.create_table(
        "small_livestock_losses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("loss_date", sa.Date(), nullable=False),
        sa.Column("livestock_type", sa.String(length=20), nullable=False),
        sa.Column("animal_category", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unnatural_loss", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("herder_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "livestock_type IN ('SHEEP','GOAT')", name="ck_small_loss_type"
        ),
        sa.CheckConstraint("quantity > 0", name="ck_small_loss_positive"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["herder_id"],
            ["herders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("small_livestock_losses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_livestock_losses_animal_category"),
            ["animal_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_losses_created_by"),
            ["created_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_losses_livestock_type"),
            ["livestock_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_losses_loss_date"),
            ["loss_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_small_livestock_losses_updated_by"),
            ["updated_by"],
            unique=False,
        )

    op.create_table(
        "horse_group_transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.String(length=36), nullable=False),
        sa.Column("from_group_id", sa.String(length=36), nullable=True),
        sa.Column("to_group_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=36), nullable=False),
        sa.Column("changed_by_name", sa.String(length=100), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_group_id"],
            ["horse_groups.id"],
        ),
        sa.ForeignKeyConstraint(["horse_id"], ["horses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["to_group_id"],
            ["horse_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("horse_group_transfers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_horse_group_transfers_changed_at"),
            ["changed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_horse_group_transfers_changed_by"),
            ["changed_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_horse_group_transfers_horse_id"), ["horse_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("horse_group_transfers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_horse_group_transfers_horse_id"))
        batch_op.drop_index(batch_op.f("ix_horse_group_transfers_changed_by"))
        batch_op.drop_index(batch_op.f("ix_horse_group_transfers_changed_at"))

    op.drop_table("horse_group_transfers")
    with op.batch_alter_table("small_livestock_losses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_livestock_losses_updated_by"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_losses_loss_date"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_losses_livestock_type"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_losses_created_by"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_losses_animal_category"))

    op.drop_table("small_livestock_losses")
    with op.batch_alter_table("horses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_horses_sex"))
        batch_op.drop_index(batch_op.f("ix_horses_mother_id"))
        batch_op.drop_index(batch_op.f("ix_horses_male_status"))
        batch_op.drop_index(batch_op.f("ix_horses_group_id"))
        batch_op.drop_index(batch_op.f("ix_horses_father_id"))
        batch_op.drop_index(batch_op.f("ix_horses_current_status"))
        batch_op.drop_index(batch_op.f("ix_horses_color"))
        batch_op.drop_index(batch_op.f("ix_horses_birth_year"))

    op.drop_table("horses")
    with op.batch_alter_table("cattle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cattle_sex"))
        batch_op.drop_index(batch_op.f("ix_cattle_mother_id"))
        batch_op.drop_index(batch_op.f("ix_cattle_is_bull"))
        batch_op.drop_index(batch_op.f("ix_cattle_ear_tag"))
        batch_op.drop_index(batch_op.f("ix_cattle_current_status"))
        batch_op.drop_index(batch_op.f("ix_cattle_color"))
        batch_op.drop_index(batch_op.f("ix_cattle_birth_year"))

    op.drop_table("cattle")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_refresh_token_hash"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_expires_at"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("small_livestock_counts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_livestock_counts_updated_by"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_counts_created_by"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_counts_count_type"))
        batch_op.drop_index(batch_op.f("ix_small_livestock_counts_count_date"))

    op.drop_table("small_livestock_counts")
    with op.batch_alter_table("inventory_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_snapshots_snapshot_date"))
        batch_op.drop_index(batch_op.f("ix_inventory_snapshots_module"))
        batch_op.drop_index(batch_op.f("ix_inventory_snapshots_created_by"))

    op.drop_table("inventory_snapshots")
    with op.batch_alter_table("image_assets", schema=None) as batch_op:
        batch_op.drop_index("ix_images_owner")
        batch_op.drop_index(batch_op.f("ix_image_assets_created_by"))
        batch_op.drop_index(batch_op.f("ix_image_assets_checksum_sha256"))

    op.drop_table("image_assets")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_user_id"))

    op.drop_table("idempotency_records")
    with op.batch_alter_table("horse_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_horse_groups_name"))
        batch_op.drop_index(batch_op.f("ix_horse_groups_is_active"))

    op.drop_table("horse_groups")
    with op.batch_alter_table("herders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_herders_updated_by"))
        batch_op.drop_index(batch_op.f("ix_herders_module"))
        batch_op.drop_index(batch_op.f("ix_herders_is_active"))
        batch_op.drop_index(batch_op.f("ix_herders_first_name"))
        batch_op.drop_index(batch_op.f("ix_herders_created_by"))

    op.drop_table("herders")
    with op.batch_alter_table("finance_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finance_entries_updated_by"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_livestock_module"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_entry_type"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_entry_date"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_created_by"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_category"))
        batch_op.drop_index(batch_op.f("ix_finance_entries_archived_at"))

    op.drop_table("finance_entries")
    op.drop_table("dashboard_preferences")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_username"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_role"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_request_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_module"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_is_active"))

    op.drop_table("users")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_username"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_created_at"))
        batch_op.drop_index("ix_login_attempt_lookup")

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
